# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2019_04_26_123873) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "hstore"
  enable_extension "pg_trgm"
  enable_extension "plpgsql"

  create_table "active_storage_attachments", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.bigint "record_id", null: false
    t.bigint "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end

  create_table "active_storage_blobs", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.bigint "byte_size", null: false
    t.string "checksum", null: false
    t.datetime "created_at", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end

  create_table "adjustments", force: :cascade do |t|
    t.json "data"
    t.string "program_title"
    t.string "loan_category"
    t.integer "program_ids", default: [], array: true
    t.integer "program_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "admin_users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "role", default: "admin_users", null: false
    t.index ["email"], name: "index_admin_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_admin_users_on_reset_password_token", unique: true
  end

  create_table "auto_responders", force: :cascade do |t|
    t.string "subject"
    t.text "template"
    t.boolean "status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["subject"], name: "index_auto_responders_on_subject"
  end

  create_table "banks", force: :cascade do |t|
    t.string "name"
    t.integer "nmls"
    t.string "phone"
    t.string "address1"
    t.string "address2"
    t.string "city"
    t.string "state_code"
    t.string "zip"
    t.string "state_eligibility"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "calculator_home_affordabilities", force: :cascade do |t|
    t.date "date", null: false
    t.string "state_code", null: false
    t.float "home_price_index", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "calculator_home_insurances", force: :cascade do |t|
    t.string "state_code", null: false
    t.float "insurance_rate", null: false
    t.float "avg_annual_insurance", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "calculator_price_to_rent_ratios", force: :cascade do |t|
    t.string "state_code", null: false
    t.float "price_rent_ratio", null: false
    t.string "city", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "calculator_property_taxes", force: :cascade do |t|
    t.string "state_code"
    t.float "tax_rate"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "cities", force: :cascade do |t|
    t.string "city"
    t.string "state_code"
    t.integer "zip"
    t.float "latitude"
    t.float "longitude"
    t.string "county"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["state_code", "city"], name: "index_cities_on_state_code_and_city"
    t.index ["state_code", "latitude", "longitude"], name: "index_cities_on_state_code_and_latitude_and_longitude"
    t.index ["zip"], name: "index_cities_on_zip", unique: true
  end

  create_table "cms_pages", force: :cascade do |t|
    t.string "page_name"
    t.text "page_content"
    t.string "page_slug"
    t.string "meta_title"
    t.text "meta_description"
    t.boolean "status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["page_slug"], name: "index_cms_pages_on_page_slug", unique: true
  end

  create_table "error_logs", force: :cascade do |t|
    t.text "details"
    t.integer "column"
    t.integer "row"
    t.string "loan_category"
    t.integer "sheet_id"
    t.boolean "status", default: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "bank_name"
    t.text "error_detail"
  end

  create_table "experts", force: :cascade do |t|
    t.string "first_name"
    t.string "last_name"
    t.string "phone"
    t.string "email", null: false
    t.string "state"
    t.string "city"
    t.string "license_number"
    t.string "specialty"
    t.string "website"
    t.string "image_file_name"
    t.string "image_content_type"
    t.integer "image_file_size"
    t.datetime "image_updated_at"
    t.integer "zip"
    t.integer "loan_type"
    t.boolean "verified", default: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["city"], name: "index_experts_on_city"
    t.index ["email"], name: "index_experts_on_email", unique: true
    t.index ["state"], name: "index_experts_on_state"
  end

  create_table "factual_mortgage_companies", force: :cascade do |t|
    t.string "factual_id"
    t.string "name"
    t.string "address"
    t.string "address_extended"
    t.string "city"
    t.string "state"
    t.integer "zip"
    t.string "country"
    t.string "neighborhoods"
    t.float "latitude"
    t.float "longitude"
    t.string "phone"
    t.string "fax"
    t.string "email"
    t.string "website"
    t.text "hours"
    t.string "hours_display"
    t.string "citysearch1_id"
    t.string "citysearch1_url"
    t.string "citysearch1_description"
    t.string "citysearch1_reviews"
    t.string "citysearch2_id"
    t.string "citysearch2_url"
    t.string "citysearch2_description"
    t.string "citysearch2_reviews"
    t.string "citysearch3_id"
    t.string "citysearch3_url"
    t.string "citysearch3_description"
    t.string "citysearch3_reviews"
    t.string "facebook1_id"
    t.string "facebook1_url"
    t.string "facebook1_description"
    t.string "facebook1_profile"
    t.string "facebook2_id"
    t.string "facebook2_url"
    t.string "facebook2_description"
    t.string "facebook2_profile"
    t.string "facebook3_id"
    t.string "facebook3_url"
    t.string "facebook3_description"
    t.string "facebook3_profile"
    t.string "foursquare1_id"
    t.string "foursquare1_url"
    t.string "foursquare1_description"
    t.string "foursquare2_id"
    t.string "foursquare2_url"
    t.string "foursquare2_description"
    t.string "foursquare3_id"
    t.string "foursquare3_url"
    t.string "foursquare3_description"
    t.string "insiderpages1_id"
    t.string "insiderpages1_url"
    t.string "insiderpages1_description"
    t.string "insiderpages2_id"
    t.string "insiderpages2_url"
    t.string "insiderpages2_description"
    t.string "insiderpages3_id"
    t.string "insiderpages3_url"
    t.string "insiderpages3_description"
    t.string "instagram1_id"
    t.string "instagram1_url"
    t.string "instagram1_description"
    t.string "instagram2_id"
    t.string "instagram2_url"
    t.string "instagram2_description"
    t.string "instagram3_id"
    t.string "instagram3_url"
    t.string "instagram3_description"
    t.string "superpages1_id"
    t.string "superpages1_url"
    t.string "superpages1_description"
    t.string "superpages1_reviews"
    t.string "superpages2_id"
    t.string "superpages2_url"
    t.string "superpages2_description"
    t.string "superpages2_reviews"
    t.string "superpages3_id"
    t.string "superpages3_url"
    t.string "superpages3_description"
    t.string "superpages3_reviews"
    t.string "twitter1_id"
    t.string "twitter1_url"
    t.string "twitter1_description"
    t.string "twitter2_id"
    t.string "twitter2_url"
    t.string "twitter2_description"
    t.string "twitter3_id"
    t.string "twitter3_url"
    t.string "twitter3_description"
    t.string "wikipedia1_id"
    t.string "wikipedia1_url"
    t.string "wikipedia1_description"
    t.string "wikipedia2_id"
    t.string "wikipedia2_url"
    t.string "wikipedia2_description"
    t.string "wikipedia3_id"
    t.string "wikipedia3_url"
    t.string "wikipedia3_description"
    t.string "yahoolocal1_id"
    t.string "yahoolocal1_url"
    t.string "yahoolocal1_description"
    t.string "yahoolocal1_reviews"
    t.string "yahoolocal2_id"
    t.string "yahoolocal2_url"
    t.string "yahoolocal2_description"
    t.string "yahoolocal2_reviews"
    t.string "yahoolocal3_id"
    t.string "yahoolocal3_url"
    t.string "yahoolocal3_description"
    t.string "yahoolocal3_reviews"
    t.string "yellowpages1_id"
    t.string "yellowpages1_url"
    t.string "yellowpages1_description"
    t.string "yellowpages2_id"
    t.string "yellowpages2_url"
    t.string "yellowpages2_description"
    t.string "yellowpages3_id"
    t.string "yellowpages3_url"
    t.string "yellowpages3_description"
    t.string "yelp1_id"
    t.string "yelp1_url"
    t.string "yelp1_description"
    t.string "yelp1_reviews"
    t.string "yelp2_id"
    t.string "yelp2_url"
    t.string "yelp2_description"
    t.string "yelp2_reviews"
    t.string "yelp3_id"
    t.string "yelp3_url"
    t.string "yelp3_description"
    t.string "yelp3_reviews"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["factual_id"], name: "index_factual_mortgage_companies_on_factual_id", unique: true
    t.index ["name"], name: "index_factual_mortgage_companies_on_name"
    t.index ["state", "city"], name: "index_factual_mortgage_companies_on_state_and_city"
    t.index ["state", "latitude", "longitude"], name: "index_mortgage_companies_on_state_and_latitude_and_longitude"
  end

  create_table "fannie_mae_loan_originations", force: :cascade do |t|
    t.string "loan_identifier"
    t.string "origination_channel"
    t.string "seller_name"
    t.float "original_interest_rate"
    t.integer "original_upb"
    t.integer "original_loan_term"
    t.datetime "origination_date"
    t.datetime "first_payment_date"
    t.integer "original_loan_to_value_ltv"
    t.integer "original_combined_loan_to_value_cltv"
    t.integer "number_of_borrowers"
    t.integer "original_debt_to_income_ratio"
    t.integer "borrower_credit_score_at_origination"
    t.boolean "first_time_home_buyer_indicator"
    t.string "loan_purpose"
    t.string "property_type"
    t.integer "number_of_units"
    t.string "occupancy_type"
    t.string "property_state"
    t.string "zip_code_short"
    t.integer "primary_mortage_insurance_percent"
    t.string "product_type"
    t.integer "co_borrower_credit_score_at_origination"
    t.integer "mortage_insurance_type"
    t.boolean "relocation_mortage_indicator"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "fdic_bank_assets_sold_and_securitizeds", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "szlnres"
    t.integer "szlnhel"
    t.integer "szlncrcd"
    t.integer "szlauto"
    t.integer "szlncon"
    t.integer "szlnci"
    t.integer "szlnoth"
    t.integer "sz30res"
    t.integer "sz30hel"
    t.integer "sz30crcd"
    t.integer "sz30auto"
    t.integer "sz30con"
    t.integer "sz30ci"
    t.integer "sz30oth"
    t.integer "sz90res"
    t.integer "sz90hel"
    t.integer "sz90crcd"
    t.integer "sz90auto"
    t.integer "sz90con"
    t.integer "sz90ci"
    t.integer "sz90oth"
    t.integer "szdrres"
    t.integer "szdrhel"
    t.integer "szdrcrcd"
    t.integer "szdrauto"
    t.integer "szdrcon"
    t.integer "szdrci"
    t.integer "szdroth"
    t.integer "szcrres"
    t.integer "szcrhel"
    t.integer "szcrcrcd"
    t.integer "szcrauto"
    t.integer "szcrcon"
    t.integer "szcrci"
    t.integer "szcroth"
    t.integer "asdrres"
    t.integer "asdrhel"
    t.integer "asdrcrcd"
    t.integer "asdrauto"
    t.integer "asdrcons"
    t.integer "asdrci"
    t.integer "asdroth"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_bank_assets_sold_and_securitizeds_on_cert"
  end

  create_table "fdic_calculations", force: :cascade do |t|
    t.integer "cert"
    t.float "m_idscod"
    t.float "m_sccmmb"
    t.float "m_scmtgbk"
    t.float "m_idscgtpc"
    t.float "m_idsccmo"
    t.float "m_idsccmt"
    t.float "m_sccmpt"
    t.float "m_sccmot"
    t.float "m_sccptg"
    t.float "m_intanmsr"
    t.float "m_intangcc"
    t.float "m_tpiremtg"
    t.float "m_teremtg"
    t.float "m_toremtg"
    t.float "m_lnlsgr"
    t.float "m_lnre"
    t.float "p_p3conoth"
    t.float "p_p9conoth"
    t.float "p_naconoth"
    t.float "p_lcon"
    t.float "p_p3lcon"
    t.float "p_p9lcon"
    t.float "p_nalcon"
    t.float "p_szlncon"
    t.float "p_sz30con"
    t.float "p_sz90con"
    t.float "p_szdrcon"
    t.float "p_szcrcon"
    t.float "p_asdrcons"
    t.float "p_sziocon"
    t.float "p_szssccon"
    t.float "p_idslccon"
    t.float "p_encecon"
    t.float "p_ascecons"
    t.float "p_szuccon"
    t.float "p_ucszcon"
    t.float "p_drconoth"
    t.float "p_crconoth"
    t.float "p_ntconoth"
    t.float "a_lnauto"
    t.float "a_p3auto"
    t.float "a_p9auto"
    t.float "a_naauto"
    t.float "a_szlauto"
    t.float "a_sz30auto"
    t.float "a_sz90auto"
    t.float "a_szdrauto"
    t.float "a_asdrauto"
    t.float "a_szioauto"
    t.float "a_szsscaut"
    t.float "a_idslcaut"
    t.float "a_enceauto"
    t.float "a_asceauto"
    t.float "a_szucauto"
    t.float "a_ucszauto"
    t.float "a_drauto"
    t.float "a_crauto"
    t.float "a_ntauto"
    t.float "a_lnlsgr"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.float "a_szcrauto"
    t.index ["cert"], name: "index_fdic_calculations_on_cert", unique: true
  end

  create_table "fdic_carrying_amount_of_assets_covered_by_fdic_loss_share_agree", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "lsalnls"
    t.integer "lrecons"
    t.integer "lreag"
    t.integer "lreres"
    t.integer "lremult"
    t.integer "lrenres"
    t.integer "lci"
    t.integer "lcon"
    t.integer "lag"
    t.integer "loth"
    t.integer "lsaore"
    t.integer "loregty"
    t.integer "lsascdbt"
    t.integer "lsaoa"
    t.integer "p3ltot"
    t.integer "p3lrecon"
    t.integer "p3lreag"
    t.integer "p3lreres"
    t.integer "p3lremul"
    t.integer "p3lrenrs"
    t.integer "p3lci"
    t.integer "p3lcon"
    t.integer "p3lag"
    t.integer "p3loth"
    t.integer "p3lgty"
    t.integer "p9ltot"
    t.integer "p9lrecon"
    t.integer "p9lreag"
    t.integer "p9lreres"
    t.integer "p9lremul"
    t.integer "p9lrenrs"
    t.integer "p9lci"
    t.integer "p9lcon"
    t.integer "p9lag"
    t.integer "p9loth"
    t.integer "p9lgty"
    t.integer "naltot"
    t.integer "nalrecon"
    t.integer "nalreag"
    t.integer "nalreres"
    t.integer "nalremul"
    t.integer "nalrenrs"
    t.integer "nalci"
    t.integer "nalcon"
    t.integer "nalag"
    t.integer "naloth"
    t.integer "nalgty"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_covered_by_fdic_loss_share_agreements_on_cert"
  end

  create_table "fdic_goodwill_and_other_intangibles", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "intan"
    t.integer "intangw"
    t.integer "intanmsr"
    t.integer "intangcc"
    t.integer "intangao"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_goodwill_and_other_intangibles_on_cert"
  end

  create_table "fdic_institutions", force: :cascade do |t|
    t.string "stname"
    t.integer "cert"
    t.string "docket"
    t.string "active"
    t.string "address"
    t.string "asset"
    t.string "bkclass"
    t.string "changec1"
    t.string "changec2"
    t.string "changec3"
    t.string "changec4"
    t.string "changec5"
    t.string "charter"
    t.string "chrtagnt"
    t.string "conserve"
    t.string "city"
    t.string "clcode"
    t.string "cmsa_no"
    t.string "cmsa"
    t.string "county"
    t.string "dateupdt"
    t.string "denovo"
    t.string "dep"
    t.string "effdate"
    t.string "endefymd"
    t.string "eq"
    t.string "estymd"
    t.string "fdicdbs"
    t.string "fdicregn"
    t.string "fdicsupv"
    t.string "fed"
    t.string "fed_rssd"
    t.string "fedchrtr"
    t.string "fldoff"
    t.string "iba"
    t.string "inactive"
    t.string "insagnt1"
    t.string "insagnt2"
    t.string "insdate"
    t.string "instcrcd"
    t.string "insbif"
    t.string "inscoml"
    t.string "insdif"
    t.string "insfdic"
    t.string "inssaif"
    t.string "inssave"
    t.string "msa_no"
    t.string "msa"
    t.string "name"
    t.string "newcert"
    t.string "oakar"
    t.string "otsdist"
    t.string "otsregnm"
    t.string "procdate"
    t.string "qbprcoml"
    t.string "regagnt"
    t.string "repdte"
    t.string "risdate"
    t.string "stchrtr"
    t.string "roa"
    t.string "roaq"
    t.string "roe"
    t.string "roeq"
    t.string "rundate"
    t.string "sasser"
    t.string "law_sasser_flg"
    t.string "stalp"
    t.string "stcnty"
    t.string "stnum"
    t.string "webaddr"
    t.integer "zip"
    t.string "suprv_fd"
    t.string "occdist"
    t.string "uninum"
    t.string "ultcert"
    t.string "cfpbeffdte"
    t.string "cfpbenddte"
    t.string "regagent2"
    t.string "offices"
    t.string "certcons"
    t.string "parcert"
    t.string "cityhcr"
    t.string "depdom"
    t.string "form31"
    t.string "hctmult"
    t.string "instag"
    t.string "mutual"
    t.string "namehcr"
    t.string "netinc"
    t.string "netincq"
    t.string "offdom"
    t.string "offfor"
    t.string "offoa"
    t.string "rssdhcr"
    t.string "stalphcr"
    t.string "stmult"
    t.string "subchaps"
    t.string "roaptx"
    t.string "roaptxq"
    t.string "trust"
    t.string "specgrp"
    t.string "specgrpn"
    t.string "tract"
    t.string "csa"
    t.string "csa_no"
    t.string "csa_flg"
    t.string "cbsa"
    t.string "cbsa_no"
    t.string "cbsa_metro_name"
    t.string "cbsa_metro"
    t.string "cbsa_metro_flg"
    t.string "cbsa_micro_flg"
    t.string "cbsa_div"
    t.string "cbsa_div_no"
    t.string "cbsa_div_flg"
    t.string "cb"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "used"
    t.index ["cert"], name: "index_fdic_institutions_on_cert", unique: true
    t.index ["name"], name: "index_fdic_institutions_on_name"
    t.index ["stname", "city"], name: "index_fdic_institutions_on_stname_and_city"
  end

  create_table "fdic_loan_charge_offs_and_recoveries", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "drlnls"
    t.integer "drre"
    t.integer "drrenus"
    t.integer "iddrredm"
    t.integer "drrecons"
    t.integer "drrecnfm"
    t.integer "drrecnot"
    t.integer "drreag"
    t.integer "drreres"
    t.integer "drremult"
    t.integer "drrenres"
    t.integer "drrenrow"
    t.integer "drrenrot"
    t.integer "drrefor"
    t.integer "drdep"
    t.integer "drdepnus"
    t.integer "drag"
    t.integer "drci"
    t.integer "drcon"
    t.integer "drcrcd"
    t.integer "drauto"
    t.integer "drconoth"
    t.integer "drforgv"
    t.integer "drother"
    t.integer "drls"
    t.integer "dragsm"
    t.integer "crlnls"
    t.integer "crre"
    t.integer "crrenus"
    t.integer "idcrredm"
    t.integer "crrecons"
    t.integer "crrecnfm"
    t.integer "crrecnot"
    t.integer "crreag"
    t.integer "crreres"
    t.integer "crremult"
    t.integer "crrenres"
    t.integer "crrenrow"
    t.integer "crrenrot"
    t.integer "crrefor"
    t.integer "crdep"
    t.integer "crdepnus"
    t.integer "crag"
    t.integer "crci"
    t.integer "crcon"
    t.integer "crcrcd"
    t.integer "crauto"
    t.integer "crconoth"
    t.integer "crforgv"
    t.integer "crother"
    t.integer "crls"
    t.integer "cragsm"
    t.integer "ntlnls"
    t.integer "ntre"
    t.integer "ntrenus"
    t.integer "idntredm"
    t.integer "ntrecons"
    t.integer "ntrecnfm"
    t.integer "ntrecnot"
    t.integer "ntreag"
    t.integer "ntreres"
    t.integer "ntremult"
    t.integer "ntrenres"
    t.integer "ntrenrow"
    t.integer "ntrenrot"
    t.integer "ntrefor"
    t.integer "ntdep"
    t.integer "ntdepnus"
    t.integer "ntag"
    t.integer "ntci"
    t.integer "ntcinus"
    t.integer "ntcon"
    t.integer "ntcrcd"
    t.integer "ntauto"
    t.integer "ntconoth"
    t.integer "ntforgv"
    t.integer "ntother"
    t.integer "ntls"
    t.integer "ntagsm"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_loan_charge_offs_and_recoveries_on_cert"
  end

  create_table "fdic_maximum_amount_of_credit_exposure_retaineds", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "sziores"
    t.integer "sziohel"
    t.integer "sziocrcd"
    t.integer "szioauto"
    t.integer "sziocon"
    t.integer "szioci"
    t.integer "sziooth"
    t.integer "szsscres"
    t.integer "szsschel"
    t.integer "szssccrd"
    t.integer "szsscaut"
    t.integer "szssccon"
    t.integer "szsscci"
    t.integer "szsscoth"
    t.integer "idslcres"
    t.integer "idslchel"
    t.integer "idslcccd"
    t.integer "idslcaut"
    t.integer "idslccon"
    t.integer "idslccci"
    t.integer "idslcoth"
    t.integer "enceres"
    t.integer "encehel"
    t.integer "encecrcd"
    t.integer "enceauto"
    t.integer "encecon"
    t.integer "enceci"
    t.integer "enceoth"
    t.integer "asceres"
    t.integer "ascehel"
    t.integer "ascecrcd"
    t.integer "asceauto"
    t.integer "ascecons"
    t.integer "asceci"
    t.integer "asceoth"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_maximum_amount_of_credit_exposure_retaineds_on_cert"
  end

  create_table "fdic_net_loans_and_leases", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "lnlsnet"
    t.integer "lnatres"
    t.integer "lnlsgr"
    t.integer "lncontra"
    t.integer "idlnls"
    t.integer "lnre"
    t.integer "lnredom"
    t.integer "lnrecons"
    t.integer "lnrenres"
    t.integer "lnrenrow"
    t.integer "lnrenrot"
    t.integer "lnremult"
    t.integer "lnreres"
    t.integer "lnreag"
    t.integer "lnrefor"
    t.integer "lnag"
    t.integer "lnci"
    t.integer "lncinus"
    t.integer "lncon"
    t.integer "lncrcd"
    t.integer "lnconrp"
    t.integer "lnauto"
    t.integer "lnconoth"
    t.integer "lnotci"
    t.integer "lnfg"
    t.integer "lnmuni"
    t.integer "idothlns"
    t.integer "ls"
    t.integer "lndepac"
    t.integer "lncomre"
    t.integer "lnrenus"
    t.integer "rslnltot"
    t.integer "rslnls"
    t.integer "lnrecnfm"
    t.integer "lnrecnot"
    t.integer "rb2lnres"
    t.integer "lnlsgrf"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_net_loans_and_leases_on_cert"
  end

  create_table "fdic_past_due_and_nonaccrual_assets", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "p3asset"
    t.integer "p3re"
    t.integer "p3renus"
    t.integer "idp3redm"
    t.integer "p3recons"
    t.integer "p3recnfm"
    t.integer "p3recnot"
    t.integer "p3reag"
    t.integer "p3reres"
    t.integer "p3remult"
    t.integer "p3renres"
    t.integer "p3renrow"
    t.integer "p3renrot"
    t.integer "p3refor"
    t.integer "p3dep"
    t.integer "p3depnus"
    t.integer "p3ag"
    t.integer "p3ci"
    t.integer "p3cinus"
    t.integer "p3con"
    t.integer "p3crcd"
    t.integer "p3auto"
    t.integer "p3conoth"
    t.integer "p3fg"
    t.integer "p3othln"
    t.integer "p3ls"
    t.integer "p3scdebt"
    t.integer "p3agsm"
    t.integer "p3lnsale"
    t.integer "p3gtypar"
    t.integer "p3ltot"
    t.integer "p9asset"
    t.integer "p9re"
    t.integer "p9renus"
    t.integer "idp9redm"
    t.integer "p9recons"
    t.integer "p9recnfm"
    t.integer "p9recnot"
    t.integer "p9reag"
    t.integer "p9reres"
    t.integer "p9remult"
    t.integer "p9renres"
    t.integer "p9renrow"
    t.integer "p9renrot"
    t.integer "p9refor"
    t.integer "p9dep"
    t.integer "p9depnus"
    t.integer "p9ag"
    t.integer "p9ci"
    t.integer "p9cinus"
    t.integer "p9con"
    t.integer "p9crcd"
    t.integer "p9auto"
    t.integer "p9conoth"
    t.integer "p9fg"
    t.integer "p9othln"
    t.integer "p9ls"
    t.integer "p9scdebt"
    t.integer "p9agsm"
    t.integer "p9lnsale"
    t.integer "p9gtypar"
    t.integer "p9ltot"
    t.integer "naasset"
    t.integer "nare"
    t.integer "narenus"
    t.integer "idnaredm"
    t.integer "narecons"
    t.integer "narecnfm"
    t.integer "narecnot"
    t.integer "nareag"
    t.integer "nareres"
    t.integer "naremult"
    t.integer "narenres"
    t.integer "narenrow"
    t.integer "narenrot"
    t.integer "narefor"
    t.integer "nadep"
    t.integer "nadepnus"
    t.integer "naag"
    t.integer "naci"
    t.integer "nacinus"
    t.integer "nacon"
    t.integer "nacrcd"
    t.integer "naauto"
    t.integer "naconoth"
    t.integer "nafg"
    t.integer "naothln"
    t.integer "nals"
    t.integer "nascdebt"
    t.integer "naagsm"
    t.integer "nalnsale"
    t.integer "nagtypar"
    t.integer "naltot"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_past_due_and_nonaccrual_assets_on_cert"
  end

  create_table "fdic_securities", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "sc"
    t.integer "scus"
    t.integer "scust"
    t.integer "scage"
    t.integer "scmuni"
    t.integer "scdomo"
    t.integer "idscod"
    t.integer "sccmmb"
    t.integer "scabs"
    t.integer "scsfp"
    t.integer "scodot"
    t.integer "scford"
    t.integer "sceq"
    t.integer "idahta"
    t.integer "scres"
    t.integer "scpledge"
    t.integer "scmtgbk"
    t.integer "idscgtpc"
    t.integer "scgty"
    t.integer "scodpc"
    t.integer "idsccmo"
    t.integer "sccol"
    t.integer "scodpi"
    t.integer "idsccmt"
    t.integer "sccmpt"
    t.integer "sccmot"
    t.integer "scha"
    t.integer "scaf"
    t.integer "scrdebt"
    t.integer "scsnhaa"
    t.integer "scsnhaf"
    t.integer "trade"
    t.integer "idtrrval"
    t.integer "trlreval"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_securities_on_cert"
  end

  create_table "fdic_total_managed_assets_held_in_fiduciary_accounts", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "trpower"
    t.integer "trexer"
    t.integer "tract"
    t.integer "tpimatot"
    t.integer "tpini"
    t.integer "tpii"
    t.integer "tpiscus"
    t.integer "tpiscmun"
    t.integer "tpimmf"
    t.integer "tpieqf"
    t.integer "tpiothf"
    t.integer "tpitrf"
    t.integer "tpisto"
    t.integer "tpiothb"
    t.integer "tpiuf"
    t.integer "tpicps"
    t.integer "tpiremtg"
    t.integer "tpire"
    t.integer "tpimisc"
    t.integer "tematot"
    t.integer "teni"
    t.integer "tei"
    t.integer "tescus"
    t.integer "tescmun"
    t.integer "temmf"
    t.integer "teeqf"
    t.integer "teothf"
    t.integer "tetrf"
    t.integer "testo"
    t.integer "teothb"
    t.integer "teuf"
    t.integer "tecps"
    t.integer "teremtg"
    t.integer "tere"
    t.integer "temisc"
    t.integer "tomatot"
    t.integer "toni"
    t.integer "toi"
    t.integer "toscus"
    t.integer "toscmun"
    t.integer "tommf"
    t.integer "toeqf"
    t.integer "toothf"
    t.integer "totrf"
    t.integer "tosto"
    t.integer "toothb"
    t.integer "touf"
    t.integer "tocps"
    t.integer "toremtg"
    t.integer "tore"
    t.integer "tomisc"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_total_managed_assets_in_fiduciary_accounts_on_cert"
  end

  create_table "fdic_total_unused_commitments", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "uc"
    t.integer "ucloc"
    t.integer "uccrcd"
    t.integer "uccomre"
    t.integer "uccomres"
    t.integer "uccomreu"
    t.integer "ucsc"
    t.integer "ucother"
    t.integer "ucover1"
    t.integer "sclent"
    t.integer "othoffbs"
    t.integer "partconv"
    t.integer "partacqu"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_total_unused_commitments_on_cert"
  end

  create_table "fdic_unused_commitments", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "szucres"
    t.integer "szuchel"
    t.integer "szuccrcd"
    t.integer "szucauto"
    t.integer "szuccon"
    t.integer "szucci"
    t.integer "szucoth"
    t.integer "ucszres"
    t.integer "ucszhel"
    t.integer "ucszcrcd"
    t.integer "ucszauto"
    t.integer "ucszcon"
    t.integer "ucszci"
    t.integer "ucszoth"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_unused_commitments_on_cert"
  end

  create_table "fdic_us_government_obligations", force: :cascade do |t|
    t.integer "cert"
    t.integer "docket"
    t.integer "fed_rssd"
    t.integer "rssdhcr"
    t.string "name"
    t.string "city"
    t.string "stalp"
    t.integer "zip"
    t.string "repdte"
    t.string "rundate"
    t.string "bkclass"
    t.string "address"
    t.string "namehcr"
    t.integer "offdom"
    t.integer "offfor"
    t.integer "stmult"
    t.integer "specgrp"
    t.integer "subchaps"
    t.string "county"
    t.integer "cbsa_metro"
    t.string "cbsa_metro_name"
    t.string "estymd"
    t.string "insdate"
    t.string "effdate"
    t.string "mutual"
    t.integer "parcert"
    t.integer "trust"
    t.string "regagnt"
    t.string "insagnt1"
    t.string "fdicdbs"
    t.string "fdicsupv"
    t.string "fldoff"
    t.string "fed"
    t.string "occdist"
    t.string "otsregnm"
    t.integer "offoa"
    t.integer "cb"
    t.string "inst_webaddr"
    t.integer "scage"
    t.integer "scaot"
    t.integer "scspn"
    t.integer "scfmn"
    t.integer "scgnm"
    t.integer "sccol"
    t.integer "sccptg"
    t.integer "sccmog"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cert"], name: "index_fdic_us_government_obligations_on_cert"
  end

  create_table "freddie_mac_caches", force: :cascade do |t|
    t.integer "cached_year"
    t.hstore "freddie_data"
    t.string "loan_type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "zip_prefix"
  end

  create_table "freddie_mac_loan_originations", force: :cascade do |t|
    t.integer "credit_score"
    t.datetime "first_payment_date"
    t.string "first_time_home_buyer_flag"
    t.datetime "maturity_date"
    t.integer "metropolitan_statistical_area"
    t.integer "mortgage_insurance_percentage"
    t.integer "number_of_units"
    t.string "occupancy_status"
    t.integer "original_combined_loan_to_value"
    t.integer "original_debt_to_income_ratio"
    t.integer "original_upb"
    t.integer "original_loan_to_value"
    t.float "original_interest_rate"
    t.string "channel"
    t.string "prepayment_penalty_mortgage_flag"
    t.string "product_type"
    t.string "property_state"
    t.string "property_type"
    t.integer "postal_code"
    t.string "loan_sequence_number"
    t.string "loan_purpose"
    t.integer "original_loan_term"
    t.integer "number_of_borrowers"
    t.string "seller_name"
    t.string "service_name"
    t.string "super_conforming_flag"
    t.string "pre_harp_loan_sequence_number"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["loan_sequence_number"], name: "index_freddie_mac_loan_originations_on_loan_sequence_number", unique: true
    t.index ["postal_code"], name: "index_freddie_mac_loan_originations_on_postal_code"
  end

  create_table "loan_officers", force: :cascade do |t|
    t.string "first"
    t.string "last"
    t.string "title"
    t.string "company"
    t.string "address"
    t.string "city"
    t.string "state"
    t.integer "zip"
    t.string "county"
    t.string "phone1"
    t.string "phone2"
    t.string "cell"
    t.string "website"
    t.string "email"
    t.float "latitude"
    t.float "longitude"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["company"], name: "index_loan_officers_on_company"
    t.index ["state", "city"], name: "index_loan_officers_on_state_and_city"
    t.index ["state", "latitude", "longitude"], name: "index_loan_officers_on_state_and_latitude_and_longitude"
  end

  create_table "mortgage_search_results", force: :cascade do |t|
    t.bigint "user_id"
    t.string "city"
    t.string "state"
    t.integer "zip"
    t.float "latitude"
    t.float "longitude"
    t.text "search_input"
    t.text "response"
    t.integer "search_type"
    t.integer "loan_type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["latitude", "longitude", "search_type"], name: "index_search_results_on_latitude_and_longitude_and_search_type"
    t.index ["state", "city", "search_type"], name: "index_mortgage_search_results_on_state_and_city_and_search_type"
    t.index ["user_id"], name: "index_mortgage_search_results_on_user_id"
  end

  create_table "news_articles", force: :cascade do |t|
    t.string "search_term"
    t.datetime "date_article"
    t.string "url"
    t.string "author"
    t.text "headline"
    t.string "snippet"
    t.text "text"
    t.integer "api_type"
    t.string "article_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["article_id"], name: "index_news_articles_on_article_id", unique: true
    t.index ["search_term"], name: "index_news_articles_on_search_term"
  end

  create_table "news_search_histories", force: :cascade do |t|
    t.string "search_term"
    t.datetime "last_searched_bing"
    t.datetime "last_searched_nyt"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["last_searched_bing"], name: "index_news_search_histories_on_last_searched_bing"
    t.index ["last_searched_nyt"], name: "index_news_search_histories_on_last_searched_nyt"
    t.index ["search_term"], name: "index_news_search_histories_on_search_term", unique: true
    t.index ["updated_at"], name: "index_news_search_histories_on_updated_at"
  end

  create_table "program_adjustments", force: :cascade do |t|
    t.integer "program_id"
    t.integer "adjustment_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "programs", force: :cascade do |t|
    t.integer "bank_id"
    t.integer "term"
    t.boolean "conforming", default: false
    t.boolean "fannie_mae", default: false
    t.boolean "fannie_mae_home_ready", default: false
    t.boolean "freddie_mac", default: false
    t.boolean "freddie_mac_home_possible", default: false
    t.boolean "fha", default: false
    t.boolean "va", default: false
    t.boolean "usda", default: false
    t.boolean "streamline", default: false
    t.boolean "full_doc", default: false
    t.text "adjustments"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "loan_category"
    t.json "base_rate"
    t.string "program_category"
    t.string "bank_name"
    t.string "program_name"
    t.string "rate_type"
    t.integer "sheet_id"
    t.string "loan_type"
    t.integer "lock_period", default: [], array: true
    t.string "loan_limit_type", default: [], array: true
    t.string "loan_purpose"
    t.string "arm_basic"
    t.string "arm_advanced"
    t.string "loan_size"
    t.string "fannie_mae_product"
    t.string "freddie_mac_product"
    t.integer "sub_sheet_id"
    t.boolean "du"
    t.boolean "lp"
    t.string "arm_benchmark"
    t.float "arm_margin"
  end

  create_table "sheets", force: :cascade do |t|
    t.string "name"
    t.integer "bank_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "sub_sheets", force: :cascade do |t|
    t.string "name"
    t.integer "sheet_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "user_favorites", force: :cascade do |t|
    t.bigint "user_id"
    t.integer "loan_tek_data_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["loan_tek_data_id"], name: "index_user_favorites_on_loan_tek_data_id"
    t.index ["user_id"], name: "index_user_favorites_on_user_id"
  end

  create_table "user_inputs", force: :cascade do |t|
    t.text "property_type", default: [], array: true
    t.text "financing_type", default: [], array: true
    t.text "premium_type", default: [], array: true
    t.string "ltv", default: [], array: true
    t.string "fico", default: [], array: true
    t.text "refinance_option", default: [], array: true
    t.text "misc_adjuster", default: [], array: true
    t.boolean "lpmi"
    t.integer "coverage"
    t.integer "loan_amount"
    t.string "cltv"
    t.boolean "dti"
    t.float "interest_rate"
    t.integer "lock_period"
    t.string "state"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "first_name", default: "", null: false
    t.string "last_name"
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.float "credit_score"
    t.float "down_payment"
    t.float "home_price"
    t.string "purpose"
    t.integer "zip_code"
    t.string "phone_number"
    t.bigint "last_search_id"
    t.integer "price_alert"
    t.boolean "is_active", default: true
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "social_login"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  add_foreign_key "active_storage_attachments", "active_storage_blobs", column: "blob_id"
  add_foreign_key "mortgage_search_results", "users"
  add_foreign_key "user_favorites", "users"
end
